<?php

namespace Sirecoog\AgenciaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopeRepository extends EntityRepository
{
    public function findResumen($login) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                        SELECT t,u
                        FROM SirecoogAgenciaBundle:Tope t 
                             JOIN t.usuario u
                        WHERE u.login= :login
                    ');
        $consulta->setParameter('login', $login);
        $consulta->setMaxResults(1);
        return $consulta->getSingleResult();
        
    }
}
