sirecoog_agencia_homepage:
    path:     /hello/{name}
    defaults: { _controller: SirecoogAgenciaBundle:Default:index }
    
portada:
    path: /{_locale}/{login}
    defaults: { _controller: SirecoogAgenciaBundle:Default:portada }
    requirements:
        _locale: "%Sirecoog.regla_acceso_idioma%"
        login: "%Sirecoog.regla_acceso_texto%"
    condition: "request.getClientIp() in ['::1', '127.0.0.1', 'fe80::1']  and request.headers.get('User-Agent') matches '/firefox/i'"