sirecoog_agencia:
    resource: "@SirecoogAgenciaBundle/Resources/config/routing.yml"
    prefix:   /

sirecoog_recaudo:
    resource: "@SirecoogRecaudoBundle/Resources/config/routing.yml"
    prefix:   /

sirecoog_usuario:
    resource: "@SirecoogUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

