security:
    firewalls:
        area_segura:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: 'Area segura prueba'
    access_control:
        - { path: ^/sirecoog/about, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sirecoog/*, roles: ROLE_ADMIN }
    
    providers:
        in_memory:
            memory:
                users:
                    ryan: { password: ryanp, roles: 'ROLE_USER' }
                    admin: { password: adminp, roles: 'ROLE_ADMIN' }
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext