security:
    firewalls:
        area_segura:
            pattern: ^/
            anonymous: ~
            form_login:
                provider:   usuarios_bd
                login_path: usuario_login
                check_path: usuario_login_check               
                
    access_control:
        - { path: ^/sirecoog/about, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sirecoog/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sirecoog/*, roles: ROLE_ADMIN }
        
    encoders:
        Sirecoog\UsuarioBundle\Entity\Usuario:
            algorithm: plaintext
        
    providers:
        usuarios_bd:
            entity:
                class: SirecoogUsuarioBundle:Usuario 
                property: login 
                
    
