<?php

namespace Sirecoog\RecaudoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecaudoRepository extends EntityRepository
{
}
